function get_x0(mindim, maxdim, plibs)
%GET_X0 Write x0 summaries for problems in the selected library.

if nargin < 3
    error('Usage: get_x0(mindim, maxdim, plibs)');
end

plibs = normalize_plibs(plibs);
plibs_stamp = get_plibs_stamp(plibs);
options.mindim = mindim;
options.maxdim = maxdim;
options.ptype = 'u';
matcutest_exclude_list = {'ARGTRIGLS',...
    'BROWNAL',...
    'COATING',...
    'DIAMON2DLS',...
    'DIAMON3DLS',...
    'DMN15102LS', ...
    'DMN15103LS',...
    'DMN15332LS',...
    'DMN15333LS',...
    'DMN37142LS',...
    'DMN37143LS',...
    'ERRINRSM',...
    'HYDC20LS',...
    'LRA9A',...
    'LRCOVTYPE',...
    'LUKSAN12LS',...
    'LUKSAN14LS',...
    'LUKSAN17LS',...
    'LUKSAN21LS',...
    'LUKSAN22LS',...
    'MANCINO',...
    'PENALTY2',...
    'PENALTY3',...
    'VARDIM'};
s2mpj_exclude_list = {'DIAMON2DLS',...
    'DIAMON2D',...
    'DIAMON3DLS',...
    'DIAMON3D',...
    'DMN15102LS',...
    'DMN15102',...
    'DMN15103LS',...
    'DMN15103',...
    'DMN15332LS',...
    'DMN15332',...
    'DMN15333LS',...
    'DMN15333',...
    'DMN37142LS',...
    'DMN37142',...
    'DMN37143LS',...
    'DMN37143',...
    'ROSSIMP3_mp',...
    'BAmL1SPLS',...
    'FBRAIN3LS',...
    'GAUSS1LS',...
    'GAUSS2LS',...
    'GAUSS3LS',...
    'HYDC20LS',...
    'HYDCAR6LS',...
    'LUKSAN11LS',...
    'LUKSAN12LS',...
    'LUKSAN13LS',...
    'LUKSAN14LS',...
    'LUKSAN17LS',...
    'LUKSAN21LS',...
    'LUKSAN22LS',...
    'METHANB8LS',...
    'METHANL8LS',...
    'SPINLS',...
    'VESUVIALS',...
    'VESUVIOLS',...
    'VESUVIOULS',...
    'YATP1CLS',... % The dimensions of the above problems are from 6 to 50. The following problems are from 51 to 200;
    'ARGLINA',...
    'ARGTRIGLS_100',...
    'EIGENALS_110',...
    'EIGENBLS_110',...
    'MANCINO_100',...
    'MODBEALE_200',...
    'MSQRTALS_100',...
    'MSQRTBLS_100',...
    'SENSORS_100',...
    'SPARSINE_100',...
    'SSBRYBND_100',...
    'TRIGON1_100',...
    'YATP1LS_120'};

if isequal(plibs, {'matcutest'})
    exclude_list = matcutest_exclude_list;
elseif isequal(plibs, {'s2mpj'})
    exclude_list = s2mpj_exclude_list;
else
    exclude_list = union(matcutest_exclude_list, s2mpj_exclude_list, 'stable');
end

problem_list = {};
problem_libs = {};
for i_lib = 1:numel(plibs)
    switch plibs{i_lib}
        case 's2mpj'
            current_problem_list = s2mpj_select(options);
            current_libs = repmat({'s2mpj'}, numel(current_problem_list), 1);
        case 'matcutest'
            current_problem_list = matcutest_select(options);
            current_libs = repmat({'matcutest'}, numel(current_problem_list), 1);
        otherwise
            error('Unsupported plibs value. Use ''s2mpj'', ''matcutest'', or {''matcutest'', ''s2mpj''}.');
    end

    if isstring(current_problem_list)
        current_problem_list = cellstr(current_problem_list);
    elseif ischar(current_problem_list)
        current_problem_list = {current_problem_list};
    end

    if ~isempty(exclude_list)
        is_kept = ~ismember(current_problem_list, exclude_list);
        current_problem_list = current_problem_list(is_kept);
        current_libs = current_libs(is_kept);
    end

    problem_list = [problem_list; current_problem_list(:)];
    problem_libs = [problem_libs; current_libs(:)];
end

num_problems = length(problem_list);
output_path = fullfile(fileparts(mfilename('fullpath')), ...
    sprintf('x0_summary_%d_%d_%s.txt', mindim, maxdim, plibs_stamp));

problems = cell(num_problems, 1);
x0_values = cell(num_problems, 1);
ratio_values = cell(num_problems, 1);
for i = 1:num_problems
    problem = problem_list{i};
    fprintf('Testing problem: %s\n', problem);
    switch problem_libs{i}
        case 's2mpj'
            p = s2mpj_load(problem);
        case 'matcutest'
            p = matcutest_load(problem);
    end
    x0 = p.x0;
    abs_x0 = abs(x0(:));
    max_abs = max(abs_x0);
    min_abs = min(abs_x0);
    if max_abs == 0 && min_abs == 0
        ratio = 1;
    elseif min_abs == 0
        ratio = Inf;
    else
        ratio = max_abs / min_abs;
    end
    problems{i} = problem;
    x0_values{i} = mat2str(x0(:).');
    ratio_values{i} = sprintf('%.16g', ratio);
end

problem_header = 'problem';
x0_header = 'x0';
ratio_header = 'abs_max_min_ratio';
problem_width = max(cellfun(@length, problems));
x0_width = max(cellfun(@length, x0_values));
ratio_width = max(cellfun(@length, ratio_values));
problem_width = max(problem_width, length(problem_header));
x0_width = max(x0_width, length(x0_header));
ratio_width = max(ratio_width, length(ratio_header));

fid = fopen(output_path, 'w');
if fid < 0
    error('Failed to open output file: %s', output_path);
end
fprintf(fid, '%-*s  %-*s  %-*s\n', problem_width, problem_header, x0_width, x0_header, ratio_width, ratio_header);
for i = 1:num_problems
    fprintf(fid, '%-*s  %-*s  %-*s\n', problem_width, problems{i}, x0_width, x0_values{i}, ratio_width, ratio_values{i});
end
fclose(fid);
fprintf('Wrote x0 summary to %s\n', output_path);

end

function plibs = normalize_plibs(plibs)
    if ischar(plibs)
        plibs = {plibs};
    elseif isstring(plibs)
        plibs = cellstr(plibs(:)');
    end

    plibs = lower(plibs);
    ordered_plibs = {};
    if any(strcmp(plibs, 'matcutest'))
        ordered_plibs{end + 1} = 'matcutest';
    end
    if any(strcmp(plibs, 's2mpj'))
        ordered_plibs{end + 1} = 's2mpj';
    end

    if isempty(ordered_plibs)
        plibs = unique(plibs, 'stable');
    else
        plibs = ordered_plibs;
    end
end

function plibs_stamp = get_plibs_stamp(plibs)
    if isequal(plibs, {'matcutest', 's2mpj'})
        plibs_stamp = 'matcutest_s2mpj';
    else
        plibs_stamp = strjoin(plibs, '_');
    end
end